-- Insert resume templates
INSERT INTO resume_templates (name, description, category, preview_image, template_data, is_premium) VALUES
('Professional Classic', 'Clean and traditional design perfect for corporate roles', 'professional', '/api/placeholder/300/400', '{"layout": "classic", "sections": ["header", "summary", "experience", "education", "skills"], "colors": {"primary": "#2563eb", "secondary": "#64748b"}}', false),
('Modern Minimalist', 'Sleek and contemporary design with clean typography', 'modern', '/api/placeholder/300/400', '{"layout": "minimalist", "sections": ["header", "summary", "experience", "education", "skills", "projects"], "colors": {"primary": "#000000", "secondary": "#6b7280"}}', false),
('Creative Portfolio', 'Eye-catching design for creative professionals', 'creative', '/api/placeholder/300/400', '{"layout": "creative", "sections": ["header", "summary", "experience", "education", "skills", "projects", "awards"], "colors": {"primary": "#7c3aed", "secondary": "#a855f7"}}', false),
('Executive Summary', 'Premium template for senior-level positions', 'professional', '/api/placeholder/300/400', '{"layout": "executive", "sections": ["header", "summary", "experience", "education", "skills", "achievements", "certifications"], "colors": {"primary": "#1e40af", "secondary": "#374151"}}', true),
('Tech Specialist', 'Designed specifically for technical roles', 'modern', '/api/placeholder/300/400', '{"layout": "tech", "sections": ["header", "summary", "experience", "education", "skills", "projects", "certifications"], "colors": {"primary": "#059669", "secondary": "#10b981"}}', false),
('Student Fresh', 'Perfect for recent graduates and entry-level positions', 'classic', '/api/placeholder/300/400', '{"layout": "student", "sections": ["header", "summary", "education", "experience", "skills", "projects", "volunteer"], "colors": {"primary": "#dc2626", "secondary": "#ef4444"}}', false),
('Designer Showcase', 'Visual-focused template for designers and artists', 'creative', '/api/placeholder/300/400', '{"layout": "showcase", "sections": ["header", "summary", "experience", "education", "skills", "portfolio", "awards"], "colors": {"primary": "#e11d48", "secondary": "#f43f5e"}}', true),
('Consultant Pro', 'Professional template for consultants and freelancers', 'professional', '/api/placeholder/300/400', '{"layout": "consultant", "sections": ["header", "summary", "experience", "education", "skills", "clients", "testimonials"], "colors": {"primary": "#0891b2", "secondary": "#06b6d4"}}', false);
